# Generated by Django 5.2.14 on 2026-05-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
