# Generated by Django 5.2.14 on 2026-05-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
